// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.0--dev
// source: validation_problem.proto

package errorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidationProblem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Problem       *Problem               `protobuf:"bytes,1,opt,name=problem" json:"problem,omitempty"`
	InvalidFields []*InvalidField        `protobuf:"bytes,2,rep,name=invalid_fields,json=invalidFields" json:"invalid_fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationProblem) Reset() {
	*x = ValidationProblem{}
	mi := &file_validation_problem_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationProblem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationProblem) ProtoMessage() {}

func (x *ValidationProblem) ProtoReflect() protoreflect.Message {
	mi := &file_validation_problem_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationProblem.ProtoReflect.Descriptor instead.
func (*ValidationProblem) Descriptor() ([]byte, []int) {
	return file_validation_problem_proto_rawDescGZIP(), []int{0}
}

func (x *ValidationProblem) GetProblem() *Problem {
	if x != nil {
		return x.Problem
	}
	return nil
}

func (x *ValidationProblem) GetInvalidFields() []*InvalidField {
	if x != nil {
		return x.InvalidFields
	}
	return nil
}

var File_validation_problem_proto protoreflect.FileDescriptor

const file_validation_problem_proto_rawDesc = "" +
	"\n" +
	"\x18validation_problem.proto\x12\aerrorpb\x1a\rproblem.proto\x1a\x13invalid_field.proto\"}\n" +
	"\x11ValidationProblem\x12*\n" +
	"\aproblem\x18\x01 \x01(\v2\x10.errorpb.ProblemR\aproblem\x12<\n" +
	"\x0einvalid_fields\x18\x02 \x03(\v2\x15.errorpb.InvalidFieldR\rinvalidFieldsB.Z,github.com/Zaba505/infra/pkg/errorpb;errorpbb\beditionsp\xe8\a"

var (
	file_validation_problem_proto_rawDescOnce sync.Once
	file_validation_problem_proto_rawDescData []byte
)

func file_validation_problem_proto_rawDescGZIP() []byte {
	file_validation_problem_proto_rawDescOnce.Do(func() {
		file_validation_problem_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_validation_problem_proto_rawDesc), len(file_validation_problem_proto_rawDesc)))
	})
	return file_validation_problem_proto_rawDescData
}

var file_validation_problem_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_validation_problem_proto_goTypes = []any{
	(*ValidationProblem)(nil), // 0: errorpb.ValidationProblem
	(*Problem)(nil),           // 1: errorpb.Problem
	(*InvalidField)(nil),      // 2: errorpb.InvalidField
}
var file_validation_problem_proto_depIdxs = []int32{
	1, // 0: errorpb.ValidationProblem.problem:type_name -> errorpb.Problem
	2, // 1: errorpb.ValidationProblem.invalid_fields:type_name -> errorpb.InvalidField
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_validation_problem_proto_init() }
func file_validation_problem_proto_init() {
	if File_validation_problem_proto != nil {
		return
	}
	file_problem_proto_init()
	file_invalid_field_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_validation_problem_proto_rawDesc), len(file_validation_problem_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_validation_problem_proto_goTypes,
		DependencyIndexes: file_validation_problem_proto_depIdxs,
		MessageInfos:      file_validation_problem_proto_msgTypes,
	}.Build()
	File_validation_problem_proto = out.File
	file_validation_problem_proto_goTypes = nil
	file_validation_problem_proto_depIdxs = nil
}
