// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.0--dev
// source: cpu.proto

package endpointpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CPU struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Manufacturer   *string                `protobuf:"bytes,1,opt,name=manufacturer" json:"manufacturer,omitempty"`
	ClockFrequency *int64                 `protobuf:"varint,2,opt,name=clock_frequency,json=clockFrequency" json:"clock_frequency,omitempty"` // measured in hertz
	Cores          *int64                 `protobuf:"varint,3,opt,name=cores" json:"cores,omitempty"`                                         // number of cores
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CPU) Reset() {
	*x = CPU{}
	mi := &file_cpu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPU) ProtoMessage() {}

func (x *CPU) ProtoReflect() protoreflect.Message {
	mi := &file_cpu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPU.ProtoReflect.Descriptor instead.
func (*CPU) Descriptor() ([]byte, []int) {
	return file_cpu_proto_rawDescGZIP(), []int{0}
}

func (x *CPU) GetManufacturer() string {
	if x != nil && x.Manufacturer != nil {
		return *x.Manufacturer
	}
	return ""
}

func (x *CPU) GetClockFrequency() int64 {
	if x != nil && x.ClockFrequency != nil {
		return *x.ClockFrequency
	}
	return 0
}

func (x *CPU) GetCores() int64 {
	if x != nil && x.Cores != nil {
		return *x.Cores
	}
	return 0
}

var File_cpu_proto protoreflect.FileDescriptor

const file_cpu_proto_rawDesc = "" +
	"\n" +
	"\tcpu.proto\x12\n" +
	"endpointpb\"h\n" +
	"\x03CPU\x12\"\n" +
	"\fmanufacturer\x18\x01 \x01(\tR\fmanufacturer\x12'\n" +
	"\x0fclock_frequency\x18\x02 \x01(\x03R\x0eclockFrequency\x12\x14\n" +
	"\x05cores\x18\x03 \x01(\x03R\x05coresBJZHgithub.com/Zaba505/infra/services/machine/endpoint/endpointpb;endpointpbb\beditionsp\xe8\a"

var (
	file_cpu_proto_rawDescOnce sync.Once
	file_cpu_proto_rawDescData []byte
)

func file_cpu_proto_rawDescGZIP() []byte {
	file_cpu_proto_rawDescOnce.Do(func() {
		file_cpu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cpu_proto_rawDesc), len(file_cpu_proto_rawDesc)))
	})
	return file_cpu_proto_rawDescData
}

var file_cpu_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cpu_proto_goTypes = []any{
	(*CPU)(nil), // 0: endpointpb.CPU
}
var file_cpu_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cpu_proto_init() }
func file_cpu_proto_init() {
	if File_cpu_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cpu_proto_rawDesc), len(file_cpu_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cpu_proto_goTypes,
		DependencyIndexes: file_cpu_proto_depIdxs,
		MessageInfos:      file_cpu_proto_msgTypes,
	}.Build()
	File_cpu_proto = out.File
	file_cpu_proto_goTypes = nil
	file_cpu_proto_depIdxs = nil
}
