// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.0--dev
// source: drive.proto

package endpointpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Drive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capacity      *int64                 `protobuf:"varint,1,opt,name=capacity" json:"capacity,omitempty"` // capacity in bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Drive) Reset() {
	*x = Drive{}
	mi := &file_drive_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Drive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Drive) ProtoMessage() {}

func (x *Drive) ProtoReflect() protoreflect.Message {
	mi := &file_drive_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Drive.ProtoReflect.Descriptor instead.
func (*Drive) Descriptor() ([]byte, []int) {
	return file_drive_proto_rawDescGZIP(), []int{0}
}

func (x *Drive) GetCapacity() int64 {
	if x != nil && x.Capacity != nil {
		return *x.Capacity
	}
	return 0
}

var File_drive_proto protoreflect.FileDescriptor

const file_drive_proto_rawDesc = "" +
	"\n" +
	"\vdrive.proto\x12\n" +
	"endpointpb\"#\n" +
	"\x05Drive\x12\x1a\n" +
	"\bcapacity\x18\x01 \x01(\x03R\bcapacityBJZHgithub.com/Zaba505/infra/services/machine/endpoint/endpointpb;endpointpbb\beditionsp\xe8\a"

var (
	file_drive_proto_rawDescOnce sync.Once
	file_drive_proto_rawDescData []byte
)

func file_drive_proto_rawDescGZIP() []byte {
	file_drive_proto_rawDescOnce.Do(func() {
		file_drive_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_drive_proto_rawDesc), len(file_drive_proto_rawDesc)))
	})
	return file_drive_proto_rawDescData
}

var file_drive_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_drive_proto_goTypes = []any{
	(*Drive)(nil), // 0: endpointpb.Drive
}
var file_drive_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_drive_proto_init() }
func file_drive_proto_init() {
	if File_drive_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_drive_proto_rawDesc), len(file_drive_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_drive_proto_goTypes,
		DependencyIndexes: file_drive_proto_depIdxs,
		MessageInfos:      file_drive_proto_msgTypes,
	}.Build()
	File_drive_proto = out.File
	file_drive_proto_goTypes = nil
	file_drive_proto_depIdxs = nil
}
