// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.0--dev
// source: memory_module.proto

package endpointpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MemoryModule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          *int64                 `protobuf:"varint,1,opt,name=size" json:"size,omitempty"` // measured in bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryModule) Reset() {
	*x = MemoryModule{}
	mi := &file_memory_module_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryModule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryModule) ProtoMessage() {}

func (x *MemoryModule) ProtoReflect() protoreflect.Message {
	mi := &file_memory_module_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryModule.ProtoReflect.Descriptor instead.
func (*MemoryModule) Descriptor() ([]byte, []int) {
	return file_memory_module_proto_rawDescGZIP(), []int{0}
}

func (x *MemoryModule) GetSize() int64 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

var File_memory_module_proto protoreflect.FileDescriptor

const file_memory_module_proto_rawDesc = "" +
	"\n" +
	"\x13memory_module.proto\x12\n" +
	"endpointpb\"\"\n" +
	"\fMemoryModule\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x03R\x04sizeBJZHgithub.com/Zaba505/infra/services/machine/endpoint/endpointpb;endpointpbb\beditionsp\xe8\a"

var (
	file_memory_module_proto_rawDescOnce sync.Once
	file_memory_module_proto_rawDescData []byte
)

func file_memory_module_proto_rawDescGZIP() []byte {
	file_memory_module_proto_rawDescOnce.Do(func() {
		file_memory_module_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_memory_module_proto_rawDesc), len(file_memory_module_proto_rawDesc)))
	})
	return file_memory_module_proto_rawDescData
}

var file_memory_module_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_memory_module_proto_goTypes = []any{
	(*MemoryModule)(nil), // 0: endpointpb.MemoryModule
}
var file_memory_module_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_memory_module_proto_init() }
func file_memory_module_proto_init() {
	if File_memory_module_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_memory_module_proto_rawDesc), len(file_memory_module_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_memory_module_proto_goTypes,
		DependencyIndexes: file_memory_module_proto_depIdxs,
		MessageInfos:      file_memory_module_proto_msgTypes,
	}.Build()
	File_memory_module_proto = out.File
	file_memory_module_proto_goTypes = nil
	file_memory_module_proto_depIdxs = nil
}
