// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.0--dev
// source: nic.proto

package endpointpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NIC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mac           *string                `protobuf:"bytes,1,opt,name=mac" json:"mac,omitempty"` // mac address
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NIC) Reset() {
	*x = NIC{}
	mi := &file_nic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NIC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NIC) ProtoMessage() {}

func (x *NIC) ProtoReflect() protoreflect.Message {
	mi := &file_nic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NIC.ProtoReflect.Descriptor instead.
func (*NIC) Descriptor() ([]byte, []int) {
	return file_nic_proto_rawDescGZIP(), []int{0}
}

func (x *NIC) GetMac() string {
	if x != nil && x.Mac != nil {
		return *x.Mac
	}
	return ""
}

var File_nic_proto protoreflect.FileDescriptor

const file_nic_proto_rawDesc = "" +
	"\n" +
	"\tnic.proto\x12\n" +
	"endpointpb\"\x17\n" +
	"\x03NIC\x12\x10\n" +
	"\x03mac\x18\x01 \x01(\tR\x03macBJZHgithub.com/Zaba505/infra/services/machine/endpoint/endpointpb;endpointpbb\beditionsp\xe8\a"

var (
	file_nic_proto_rawDescOnce sync.Once
	file_nic_proto_rawDescData []byte
)

func file_nic_proto_rawDescGZIP() []byte {
	file_nic_proto_rawDescOnce.Do(func() {
		file_nic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nic_proto_rawDesc), len(file_nic_proto_rawDesc)))
	})
	return file_nic_proto_rawDescData
}

var file_nic_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_nic_proto_goTypes = []any{
	(*NIC)(nil), // 0: endpointpb.NIC
}
var file_nic_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nic_proto_init() }
func file_nic_proto_init() {
	if File_nic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nic_proto_rawDesc), len(file_nic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nic_proto_goTypes,
		DependencyIndexes: file_nic_proto_depIdxs,
		MessageInfos:      file_nic_proto_msgTypes,
	}.Build()
	File_nic_proto = out.File
	file_nic_proto_goTypes = nil
	file_nic_proto_depIdxs = nil
}
