// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.0--dev
// source: register_machine_request.proto

package endpointpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterMachineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpus          []*CPU                 `protobuf:"bytes,1,rep,name=cpus" json:"cpus,omitempty"`
	MemoryModules []*MemoryModule        `protobuf:"bytes,2,rep,name=memory_modules,json=memoryModules" json:"memory_modules,omitempty"`
	Accelerators  []*Accelerator         `protobuf:"bytes,3,rep,name=accelerators" json:"accelerators,omitempty"`
	Nics          []*NIC                 `protobuf:"bytes,4,rep,name=nics" json:"nics,omitempty"`
	Drives        []*Drive               `protobuf:"bytes,5,rep,name=drives" json:"drives,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterMachineRequest) Reset() {
	*x = RegisterMachineRequest{}
	mi := &file_register_machine_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterMachineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMachineRequest) ProtoMessage() {}

func (x *RegisterMachineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_register_machine_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMachineRequest.ProtoReflect.Descriptor instead.
func (*RegisterMachineRequest) Descriptor() ([]byte, []int) {
	return file_register_machine_request_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterMachineRequest) GetCpus() []*CPU {
	if x != nil {
		return x.Cpus
	}
	return nil
}

func (x *RegisterMachineRequest) GetMemoryModules() []*MemoryModule {
	if x != nil {
		return x.MemoryModules
	}
	return nil
}

func (x *RegisterMachineRequest) GetAccelerators() []*Accelerator {
	if x != nil {
		return x.Accelerators
	}
	return nil
}

func (x *RegisterMachineRequest) GetNics() []*NIC {
	if x != nil {
		return x.Nics
	}
	return nil
}

func (x *RegisterMachineRequest) GetDrives() []*Drive {
	if x != nil {
		return x.Drives
	}
	return nil
}

var File_register_machine_request_proto protoreflect.FileDescriptor

const file_register_machine_request_proto_rawDesc = "" +
	"\n" +
	"\x1eregister_machine_request.proto\x12\n" +
	"endpointpb\x1a\x11accelerator.proto\x1a\tcpu.proto\x1a\vdrive.proto\x1a\x13memory_module.proto\x1a\tnic.proto\"\x8b\x02\n" +
	"\x16RegisterMachineRequest\x12#\n" +
	"\x04cpus\x18\x01 \x03(\v2\x0f.endpointpb.CPUR\x04cpus\x12?\n" +
	"\x0ememory_modules\x18\x02 \x03(\v2\x18.endpointpb.MemoryModuleR\rmemoryModules\x12;\n" +
	"\faccelerators\x18\x03 \x03(\v2\x17.endpointpb.AcceleratorR\faccelerators\x12#\n" +
	"\x04nics\x18\x04 \x03(\v2\x0f.endpointpb.NICR\x04nics\x12)\n" +
	"\x06drives\x18\x05 \x03(\v2\x11.endpointpb.DriveR\x06drivesBJZHgithub.com/Zaba505/infra/services/machine/endpoint/endpointpb;endpointpbb\beditionsp\xe8\a"

var (
	file_register_machine_request_proto_rawDescOnce sync.Once
	file_register_machine_request_proto_rawDescData []byte
)

func file_register_machine_request_proto_rawDescGZIP() []byte {
	file_register_machine_request_proto_rawDescOnce.Do(func() {
		file_register_machine_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_register_machine_request_proto_rawDesc), len(file_register_machine_request_proto_rawDesc)))
	})
	return file_register_machine_request_proto_rawDescData
}

var file_register_machine_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_register_machine_request_proto_goTypes = []any{
	(*RegisterMachineRequest)(nil), // 0: endpointpb.RegisterMachineRequest
	(*CPU)(nil),                    // 1: endpointpb.CPU
	(*MemoryModule)(nil),           // 2: endpointpb.MemoryModule
	(*Accelerator)(nil),            // 3: endpointpb.Accelerator
	(*NIC)(nil),                    // 4: endpointpb.NIC
	(*Drive)(nil),                  // 5: endpointpb.Drive
}
var file_register_machine_request_proto_depIdxs = []int32{
	1, // 0: endpointpb.RegisterMachineRequest.cpus:type_name -> endpointpb.CPU
	2, // 1: endpointpb.RegisterMachineRequest.memory_modules:type_name -> endpointpb.MemoryModule
	3, // 2: endpointpb.RegisterMachineRequest.accelerators:type_name -> endpointpb.Accelerator
	4, // 3: endpointpb.RegisterMachineRequest.nics:type_name -> endpointpb.NIC
	5, // 4: endpointpb.RegisterMachineRequest.drives:type_name -> endpointpb.Drive
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_register_machine_request_proto_init() }
func file_register_machine_request_proto_init() {
	if File_register_machine_request_proto != nil {
		return
	}
	file_accelerator_proto_init()
	file_cpu_proto_init()
	file_drive_proto_init()
	file_memory_module_proto_init()
	file_nic_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_register_machine_request_proto_rawDesc), len(file_register_machine_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_register_machine_request_proto_goTypes,
		DependencyIndexes: file_register_machine_request_proto_depIdxs,
		MessageInfos:      file_register_machine_request_proto_msgTypes,
	}.Build()
	File_register_machine_request_proto = out.File
	file_register_machine_request_proto_goTypes = nil
	file_register_machine_request_proto_depIdxs = nil
}
