// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.0--dev
// source: register_machine_service.proto

package endpointpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_register_machine_service_proto protoreflect.FileDescriptor

const file_register_machine_service_proto_rawDesc = "" +
	"\n" +
	"\x1eregister_machine_service.proto\x12\n" +
	"endpointpb\x1a\x1eregister_machine_request.proto\x1a\x1fregister_machine_response.proto2t\n" +
	"\x16RegisterMachineService\x12Z\n" +
	"\x0fRegisterMachine\x12\".endpointpb.RegisterMachineRequest\x1a#.endpointpb.RegisterMachineResponseBJZHgithub.com/Zaba505/infra/services/machine/endpoint/endpointpb;endpointpbb\beditionsp\xe8\a"

var file_register_machine_service_proto_goTypes = []any{
	(*RegisterMachineRequest)(nil),  // 0: endpointpb.RegisterMachineRequest
	(*RegisterMachineResponse)(nil), // 1: endpointpb.RegisterMachineResponse
}
var file_register_machine_service_proto_depIdxs = []int32{
	0, // 0: endpointpb.RegisterMachineService.RegisterMachine:input_type -> endpointpb.RegisterMachineRequest
	1, // 1: endpointpb.RegisterMachineService.RegisterMachine:output_type -> endpointpb.RegisterMachineResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_register_machine_service_proto_init() }
func file_register_machine_service_proto_init() {
	if File_register_machine_service_proto != nil {
		return
	}
	file_register_machine_request_proto_init()
	file_register_machine_response_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_register_machine_service_proto_rawDesc), len(file_register_machine_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_register_machine_service_proto_goTypes,
		DependencyIndexes: file_register_machine_service_proto_depIdxs,
	}.Build()
	File_register_machine_service_proto = out.File
	file_register_machine_service_proto_goTypes = nil
	file_register_machine_service_proto_depIdxs = nil
}
