logging:
  level: {{env "LOG_LEVEL" | default "INFO"}}

otel:
  service_name: {{env "OTEL_SERVICE_NAME"}}
  service_version: {{env "OTEL_SERVICE_VERSION"}}
  trace:
    enabled: {{env "OTEL_TRACE_ENABLED" | default false}}
    sampling: {{env "OTEL_SAMPLING" | default 0.1}}
    batch_timeout: {{env "OTEL_TRACE_BATCH_TIMEOUT" | default "10s"}}
  metric:
    enabled: {{env "OTEL_METRIC_ENABLED" | default false}}
    export_period: {{env "OTEL_METRIC_EXPORT_PERIOD" | default "60s"}}
  log:
    batch_timeout: {{env "OTEL_LOG_BATCH_TIMEOUT" | default "1s"}}

http:
  port: {{env "HTTP_PORT" | default 80}}